# Generated by Django 5.0.4 on 2024-04-20 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='codigo',
            field=models.CharField(default=10, max_length=100),
            preserve_default=False,
        ),
    ]
