# Generated by Django 5.0.4 on 2024-04-20 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_produto_codigo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='codigo',
            new_name='codigo_barras',
        ),
    ]
