# Generated by Django 5.0.4 on 2024-04-21 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_rename_codigo_produto_codigo_barras'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estoque',
            old_name='quantidade_estoque',
            new_name='quantidade',
        ),
        migrations.AddField(
            model_name='estoque',
            name='movimentacao',
            field=models.CharField(choices=[('Entrada', 'Entrada'), ('Saida', 'Saida')], default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='quantidade_estoque',
            field=models.IntegerField(default=0),
        ),
    ]
