# Generated by Django 5.0.4 on 2024-04-21 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_rename_quantidade_estoque_estoque_quantidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='quantidade_inicial',
            field=models.IntegerField(default=0),
        ),
    ]
