# Generated by Django 5.0.4 on 2024-04-21 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0005_alter_produto_quantidade_inicial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='quantidade_inicial',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
