# Generated by Django 5.0.4 on 2024-04-21 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0006_alter_produto_quantidade_inicial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='situacao',
            field=models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo')], max_length=10),
        ),
    ]
